/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libProceso_JavaProceso */

#ifndef _Included_libProceso_JavaProceso
#define _Included_libProceso_JavaProceso
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libProceso_JavaProceso
 * Method:    algoritmo_SJF_no_expulsivo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libProceso_JavaProceso_algoritmo_1SJF_1no_1expulsivo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     libProceso_JavaProceso
 * Method:    algoritmo_SJF_expulsivo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libProceso_JavaProceso_algoritmo_1SJF_1expulsivo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
